### ISSUE TITLE
Couple of comments on script size

### ISSUE THREAD

**Issue by michaelpj** [Plutonomicon/plutonomicon#10]
https://github.com/Plutonomicon/plutonomicon/blob/main/scriptsize.md#avoid-referencing-code

The compiler does dead code elimination, this is a somewhat baffling thing to say. Yes, the transitive closure of what you use is included... because you use it... so it isn't dead :thinking: 

https://github.com/Plutonomicon/plutonomicon/blob/main/scriptsize.md#avoid-referencing-data-types

`newtypes` are compiled exactly to their underlying type, so I highly doubt that they lead to bloat.

https://github.com/Plutonomicon/plutonomicon/blob/main/scriptsize.md#use-conditional-traceiffalse

As of [recently](https://github.com/input-output-hk/plutus/pull/4219), there's a plugin option which does this.

**Comment by L-as** [comment]
@michaelpj Thanks for clarifying on this. This has been some internal notes written by multiple parties.

wrt. newtypes, experimentally we've observed that there is a difference in practice. I haven't taken a look at the generated UPLC to understand why.

Thank you for opening this issue!

**Comment by L-as** [comment]
wrt. dead code elimination:
- https://github.com/input-output-hk/plutus/issues/4147

I think this is what was thought of when that part was written. How do you prefer phrasing this?

**Comment by michaelpj** [comment]
> I haven't taken a look at the generated UPLC to understand why.

You could look at the PIR.

I'd be very surprised if there is much difference. Possibly it affects what GHC does with it before we get it, but I can promise you that when we go to PIR we replace it with the underlying type.

> I think this is what was thought of when that part was written. How do you prefer phrasing this?

That's an edge case where there is a tiny bit of arguably dead code. It's totally wrong to say "we don't do any dead code elimination". And indeed the recommendation is self-contradictory: avoiding referring to code won't save you any space unless the compiler gets rid of it, aka dead code elimination.

You could just say "all the code you reference gets included, so using less code will make your scripts smaller".

**Comment by L-as** [comment]
> That's an edge case where there is a tiny bit of arguably dead code. It's totally wrong to say "we don't do any dead code elimination". And indeed the recommendation is self-contradictory: avoiding referring to code won't save you any space unless the compiler gets rid of it, aka dead code elimination.

Thanks for clarifying this, While it may be a tiny amount (~100 bytes maybe for an average dapp?), essentially every byte matters until CIP-33 lands, since the throughput of most dapps is limited by the amount of space left in the transaction after scripts.

**Comment by michaelpj** [comment]
I'm not saying it's not important. I'm just saying that it's wildly inaccurate to say "the compiler does not do any dead code elimination".
